<!-- formulario para agregar periferico -->
<form action="agregarJoyeria" method="POST" class="my-4">
    <div class="row text-center">
        <div class="col-3">
            <div class="form-group">
                <label>Marca</label>
                <input  name="marca" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Precio</label>
                <input required name="precio" type="number" class="form-control">
            </div>

        </div><div class="col-3">
            <div class="form-group">
                <label>Bañado</label>
                <input required name="bañado" type="text" class="form-control">
            </div>
        </div>

        <div class="col-2">
            <div class="form-group">
                <label>Accesorios</label>
                <select required name="accesorio" class="form-control text-center">
                <?php foreach($accesorios as $acc): ?>
                    <option value="<?= $acc->id_joya ?>"> <?= $acc->id_joya ?> </option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>