<!-- formulario para agregar periferico -->
<form action="agregarAccesorios" method="POST" class="my-4">

        </div><div class="col-3">
            <div class="form-group">
                <label>Tipo accesorio</label>
                <input required name="accesorio" type="text" class="form-control">
            </div>
        </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>